//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dex.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dex.Common.Resources.HomePageResources", typeof(HomePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the home of DexSoftware!.
        /// </summary>
        public static string StringMainTitle {
            get {
                return ResourceManager.GetString("StringMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d like to get in touch with me, you can check out the {0} section..
        /// </summary>
        public static string StringParagraphFour {
            get {
                return ResourceManager.GetString("StringParagraphFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string StringParagraphFourActionLinkText {
            get {
                return ResourceManager.GetString("StringParagraphFourActionLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I develop most of my software for both desktop and web usage, you can create a free account {0}, which you can use to log into all of the applications or try them out as a guest..
        /// </summary>
        public static string StringParagraphOne {
            get {
                return ResourceManager.GetString("StringParagraphOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string StringParagraphOneActionLinkText {
            get {
                return ResourceManager.GetString("StringParagraphOneActionLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check out all of my uploaded projects, under section {0}. Both the desktop and the web versions should be accessible through there..
        /// </summary>
        public static string StringParagraphThree {
            get {
                return ResourceManager.GetString("StringParagraphThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string StringParagraphThreeActionLinkText {
            get {
                return ResourceManager.GetString("StringParagraphThreeActionLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You could also check out my blog posts under section {0}. There you will find project updates, interesting topics and general discussion, where you could participate!.
        /// </summary>
        public static string StringParagraphTwo {
            get {
                return ResourceManager.GetString("StringParagraphTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string StringParagraphTwoActionLinkText {
            get {
                return ResourceManager.GetString("StringParagraphTwoActionLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you will find most of my recent work, including  source codes, blog posts and others..
        /// </summary>
        public static string StringSubTitle {
            get {
                return ResourceManager.GetString("StringSubTitle", resourceCulture);
            }
        }
    }
}
